PUT http://localhost:3001/api/readinglists/1 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpQG1ha2VsYS5jbyIsImlkIjoyLCJpYXQiOjE2OTIxMDE4MDd9.1j8DMPO51T3zOLuu-U3ue5rqd9ThtZ1SEmfBV_Kw2KA

{
  "read": true
}